# Провалює тест
def test_failure():
    assert False, "Тест завершується з помилкою"
